# Generated by Django 4.2 on 2023-04-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIN', models.CharField(max_length=25)),
                ('village', models.CharField(max_length=20)),
            ],
        ),
    ]
